# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.source import source_pb2 as v1_dot_source_dot_source__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/hi.source.File/Upload',
                request_serializer=v1_dot_source_dot_source__pb2.UploadReq.SerializeToString,
                response_deserializer=v1_dot_source_dot_source__pb2.UploadResp.FromString,
                _registered_method=True)
        self.Download = channel.unary_unary(
                '/hi.source.File/Download',
                request_serializer=v1_dot_source_dot_source__pb2.DownloadReq.SerializeToString,
                response_deserializer=v1_dot_source_dot_source__pb2.DownloadResp.FromString,
                _registered_method=True)


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=v1_dot_source_dot_source__pb2.UploadReq.FromString,
                    response_serializer=v1_dot_source_dot_source__pb2.UploadResp.SerializeToString,
            ),
            'Download': grpc.unary_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=v1_dot_source_dot_source__pb2.DownloadReq.FromString,
                    response_serializer=v1_dot_source_dot_source__pb2.DownloadResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.source.File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.source.File', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.source.File/Upload',
            v1_dot_source_dot_source__pb2.UploadReq.SerializeToString,
            v1_dot_source_dot_source__pb2.UploadResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.source.File/Download',
            v1_dot_source_dot_source__pb2.DownloadReq.SerializeToString,
            v1_dot_source_dot_source__pb2.DownloadResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
