syntax = "proto3";

package hi.ai;

option go_package = "github.com/HiWorld-56/hi-proto/go/hi/ai";

import "google/protobuf/empty.proto";
import "hi/options.proto";

message EndpointSetReq {
  string endpoint = 1;
}

message EndpointGetResp {
  string endpoint = 1;
}

service PluginEndpoint {
  rpc Set (EndpointSetReq) returns (google.protobuf.Empty) { option (hi.auth) = AUTH_TOKEN; } // Token鉴权
  rpc Get (google.protobuf.Empty) returns (EndpointGetResp) { option (hi.auth) = AUTH_TOKEN; } // Token鉴权
}
