syntax = "proto3";

package hi.ai;

option go_package = "github.com/HiWorld-56/hi-proto/go/hi/ai";

import "google/protobuf/empty.proto";
import "hi/common.proto";
import "hi/options.proto";

message UserACLAddReq {
  string did  = 1;
  string type = 2;
}

message UserACLDeleteReq {
  string did  = 1;
  string type = 2;
}

message UserACLListReq {
  string        did        = 1;
  string        type       = 2;
  hi.Pagination pagination = 3;
}

message UserACLListResp {
  message Unit {
    string          did         = 1;
    repeated string permissions = 2;
    string          note        = 3;
  }
  int32         total = 1;
  repeated Unit infos = 2;
}

message UserACLListTypeResp {
  repeated string types = 1;
}

message UserACLEditReq {
  string did  = 1;
  string note = 2;
}

// Token鉴权
service UserACL {
  rpc Add (UserACLAddReq) returns (google.protobuf.Empty) { option (hi.auth) = AUTH_TOKEN; }
  rpc Delete (UserACLDeleteReq) returns (google.protobuf.Empty) { option (hi.auth) = AUTH_TOKEN; }
  rpc List (UserACLListReq) returns (UserACLListResp) { option (hi.auth) = AUTH_TOKEN; }
  rpc ListTypes (google.protobuf.Empty) returns (UserACLListTypeResp) { option (hi.auth) = AUTH_TOKEN; }
  rpc Edit (UserACLEditReq) returns (google.protobuf.Empty) { option (hi.auth) = AUTH_TOKEN; }
}
