syntax = "proto3";

package hi.club;

option go_package = "github.com/HiWorld-56/hi-proto/go/hi/club";

import "google/protobuf/empty.proto";
import "hi/did/api_key.proto";
import "hi/options.proto";

// 使用token鉴权
service ApiKey {
  rpc Create (hi.did.CreateApiKeyReq) returns (hi.did.CreateApiKeyResp) { option (hi.auth) = AUTH_TOKEN; }
  rpc Edit (hi.did.EditApiKeyReq) returns (hi.did.EditApiKeyResp) { option (hi.auth) = AUTH_TOKEN; }
  rpc List (hi.did.ListApiKeyReq) returns (hi.did.ListApiKeyResp) { option (hi.auth) = AUTH_TOKEN; }
  rpc Delete (hi.did.DeleteApiKeyReq) returns (google.protobuf.Empty) { option (hi.auth) = AUTH_TOKEN; }
}
