syntax = "proto3";

package hi.club;

import "hi/common.proto";
import "hi/did/auth.proto";

option go_package = "github.com/HiWorld-56/hi-proto/gen/go/hi/club";

message LoginResp {
  hi.Entity base = 1;
  hi.AuthToken token = 2;
  hi.MqttCredentials mqtt = 3;
  hi.Entity master = 4;
}

service Auth {
  rpc RefreshToken(hi.did.RefreshTokenReq) returns (hi.AuthToken); // 不鉴权
  rpc GenerateReqId(hi.did.GenerateReqIdReq) returns (hi.RequestId); // 不鉴权
  rpc GetReqStatus(hi.RequestId) returns (hi.did.ReqStatusResp); // 不鉴权
  rpc Verify(hi.SignedData) returns (LoginResp); // Web3鉴权 / hi.did.LoginReq
}
