syntax = "proto3";

package hi.media;

option go_package = "github.com/HiWorld-56/hi-proto/go/hi/media";

import "google/protobuf/empty.proto";
import "hi/common.proto";
import "hi/did/admin.proto";

// 邀请码
service InviteCode {
  rpc Create (google.protobuf.Empty) returns (hi.did.InviteCodeCreateResp); // Token鉴权
  rpc Edit (hi.did.InviteCodeEditReq) returns (google.protobuf.Empty); // Token鉴权
  rpc List (hi.Pagination) returns (hi.did.InviteCodeListResp); // Token鉴权
  rpc Delete (hi.did.InviteCodeDeleteReq) returns (google.protobuf.Empty); // Token鉴权
  rpc Verify (hi.did.InviteCodeVerifyReq) returns (hi.AuthToken); // 不鉴权
}