syntax = "proto3";

package hi.media;

option go_package = "github.com/HiWorld-56/hi-proto/go/hi/media";

import "google/protobuf/empty.proto";
import "hi/options.proto";

message GetMediaQuotaResp {
  option (hi.audience) = VIS_SELF;
  optional uint64 total_bytes = 1 [(hi.visibility) = VIS_SELF];
  optional uint64 used_bytes = 2 [(hi.visibility) = VIS_SELF];
  optional uint64 available_bytes = 3 [(hi.visibility) = VIS_SELF];
}

service MediaQuota {
  rpc Get (google.protobuf.Empty) returns (GetMediaQuotaResp) { option (hi.auth) = AUTH_USER; }
}
