# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/club/base.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/club/base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.did import base_pb2 as v1_dot_did_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12v1/club/base.proto\x12\x07hi.club\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11v1/did/base.proto\"\"\n\x0cGetConfigReq\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"%\n\rGetConfigResp\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value2\x94\x02\n\x04\x42\x61se\x12:\n\tListCoins\x12\x16.google.protobuf.Empty\x1a\x15.hi.did.ListCoinsResp\x12\x44\n\rLastetVersion\x12\x18.hi.did.LastetVersionReq\x1a\x19.hi.did.LastetVersionResp\x12N\n\x13ListSuperAdminUsers\x12\x16.google.protobuf.Empty\x1a\x1f.hi.did.ListSuperAdminUsersResp\x12:\n\tGetConfig\x12\x15.hi.club.GetConfigReq\x1a\x16.hi.club.GetConfigRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.club.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONFIGREQ']._serialized_start=79
  _globals['_GETCONFIGREQ']._serialized_end=113
  _globals['_GETCONFIGRESP']._serialized_start=115
  _globals['_GETCONFIGRESP']._serialized_end=152
  _globals['_BASE']._serialized_start=155
  _globals['_BASE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
