# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.ai import bot_pb2 as v1_dot_ai_dot_bot__pb2
from v1.club import bot_pb2 as v1_dot_club_dot_bot__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


class BotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLLM = channel.unary_unary(
                '/hi.club.Bot/ListLLM',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListLLMResp.FromString,
                _registered_method=True)
        self.ListEmbedding = channel.unary_unary(
                '/hi.club.Bot/ListEmbedding',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListEmbeddingResp.FromString,
                _registered_method=True)
        self.ListSTT = channel.unary_unary(
                '/hi.club.Bot/ListSTT',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListSTTResp.FromString,
                _registered_method=True)
        self.ListTTS = channel.unary_unary(
                '/hi.club.Bot/ListTTS',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListTTSResp.FromString,
                _registered_method=True)
        self.BotConfig = channel.unary_unary(
                '/hi.club.Bot/BotConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.BotConfigResp.FromString,
                _registered_method=True)
        self.CreateBot = channel.unary_unary(
                '/hi.club.Bot/CreateBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.CreateBotReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.CreateBotResp.FromString,
                _registered_method=True)
        self.EditBot = channel.unary_unary(
                '/hi.club.Bot/EditBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.EditBotReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListBot = channel.unary_unary(
                '/hi.club.Bot/ListBot',
                request_serializer=v1_dot_hi__pb2.Pagination.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListBotResp.FromString,
                _registered_method=True)
        self.ListBotByDids = channel.unary_unary(
                '/hi.club.Bot/ListBotByDids',
                request_serializer=v1_dot_ai_dot_bot__pb2.ListBotByDidsReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListBotByDidsResp.FromString,
                _registered_method=True)
        self.DeleteBot = channel.unary_unary(
                '/hi.club.Bot/DeleteBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.DeleteBotReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.FindBot = channel.unary_unary(
                '/hi.club.Bot/FindBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.FindBotReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.FindBotResp.FromString,
                _registered_method=True)
        self.FindBotCount = channel.unary_unary(
                '/hi.club.Bot/FindBotCount',
                request_serializer=v1_dot_ai_dot_bot__pb2.FindBotCountReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.FindBotCountResp.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/hi.club.Bot/Transfer',
                request_serializer=v1_dot_ai_dot_bot__pb2.TransferReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdatesToDefault = channel.unary_unary(
                '/hi.club.Bot/UpdatesToDefault',
                request_serializer=v1_dot_ai_dot_bot__pb2.UpdatesToDefaultReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.FavoriteBot = channel.unary_unary(
                '/hi.club.Bot/FavoriteBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.FavoriteBotReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListFavoriteBot = channel.unary_unary(
                '/hi.club.Bot/ListFavoriteBot',
                request_serializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotResp.FromString,
                _registered_method=True)
        self.FavoriteBotListByDIDs = channel.unary_unary(
                '/hi.club.Bot/FavoriteBotListByDIDs',
                request_serializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsResp.FromString,
                _registered_method=True)
        self.BindMaster = channel.unary_unary(
                '/hi.club.Bot/BindMaster',
                request_serializer=v1_dot_club_dot_bot__pb2.BindMasterReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UnbindMaster = channel.unary_unary(
                '/hi.club.Bot/UnbindMaster',
                request_serializer=v1_dot_club_dot_bot__pb2.UnbindMasterReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BindStatus = channel.unary_unary(
                '/hi.club.Bot/BindStatus',
                request_serializer=v1_dot_club_dot_bot__pb2.BindStatusReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_bot__pb2.BindStatusResp.FromString,
                _registered_method=True)
        self.ListAllOnlineBot = channel.unary_unary(
                '/hi.club.Bot/ListAllOnlineBot',
                request_serializer=v1_dot_hi__pb2.Pagination.SerializeToString,
                response_deserializer=v1_dot_club_dot_bot__pb2.ListAllOnlineBotResp.FromString,
                _registered_method=True)
        self.ListOnlineBot = channel.unary_unary(
                '/hi.club.Bot/ListOnlineBot',
                request_serializer=v1_dot_hi__pb2.DID.SerializeToString,
                response_deserializer=v1_dot_club_dot_bot__pb2.ListOnlineBotResp.FromString,
                _registered_method=True)
        self.GetBotMaster = channel.unary_unary(
                '/hi.club.Bot/GetBotMaster',
                request_serializer=v1_dot_club_dot_bot__pb2.GetBotMasterReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_bot__pb2.GetBotMasterResp.FromString,
                _registered_method=True)


class BotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSTT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BotConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBotByDids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindBotCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatesToDefault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FavoriteBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFavoriteBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FavoriteBotListByDIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindMaster(self, request, context):
        """绑定机器人
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindMaster(self, request, context):
        """解绑机器人
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindStatus(self, request, context):
        """机器人绑定状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllOnlineBot(self, request, context):
        """在线机器人列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOnlineBot(self, request, context):
        """用户的在线机器人
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBotMaster(self, request, context):
        """机器人主人
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLLM,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListLLMResp.SerializeToString,
            ),
            'ListEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmbedding,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListEmbeddingResp.SerializeToString,
            ),
            'ListSTT': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSTT,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListSTTResp.SerializeToString,
            ),
            'ListTTS': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTTS,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListTTSResp.SerializeToString,
            ),
            'BotConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.BotConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.BotConfigResp.SerializeToString,
            ),
            'CreateBot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.CreateBotReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.CreateBotResp.SerializeToString,
            ),
            'EditBot': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.EditBotReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListBot': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBot,
                    request_deserializer=v1_dot_hi__pb2.Pagination.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListBotResp.SerializeToString,
            ),
            'ListBotByDids': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBotByDids,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.ListBotByDidsReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListBotByDidsResp.SerializeToString,
            ),
            'DeleteBot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.DeleteBotReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FindBot': grpc.unary_unary_rpc_method_handler(
                    servicer.FindBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.FindBotReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.FindBotResp.SerializeToString,
            ),
            'FindBotCount': grpc.unary_unary_rpc_method_handler(
                    servicer.FindBotCount,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.FindBotCountReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.FindBotCountResp.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.TransferReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdatesToDefault': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatesToDefault,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.UpdatesToDefaultReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FavoriteBot': grpc.unary_unary_rpc_method_handler(
                    servicer.FavoriteBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.FavoriteBotReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListFavoriteBot': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFavoriteBot,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotResp.SerializeToString,
            ),
            'FavoriteBotListByDIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.FavoriteBotListByDIDs,
                    request_deserializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsReq.FromString,
                    response_serializer=v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsResp.SerializeToString,
            ),
            'BindMaster': grpc.unary_unary_rpc_method_handler(
                    servicer.BindMaster,
                    request_deserializer=v1_dot_club_dot_bot__pb2.BindMasterReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UnbindMaster': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindMaster,
                    request_deserializer=v1_dot_club_dot_bot__pb2.UnbindMasterReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BindStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.BindStatus,
                    request_deserializer=v1_dot_club_dot_bot__pb2.BindStatusReq.FromString,
                    response_serializer=v1_dot_club_dot_bot__pb2.BindStatusResp.SerializeToString,
            ),
            'ListAllOnlineBot': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllOnlineBot,
                    request_deserializer=v1_dot_hi__pb2.Pagination.FromString,
                    response_serializer=v1_dot_club_dot_bot__pb2.ListAllOnlineBotResp.SerializeToString,
            ),
            'ListOnlineBot': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOnlineBot,
                    request_deserializer=v1_dot_hi__pb2.DID.FromString,
                    response_serializer=v1_dot_club_dot_bot__pb2.ListOnlineBotResp.SerializeToString,
            ),
            'GetBotMaster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotMaster,
                    request_deserializer=v1_dot_club_dot_bot__pb2.GetBotMasterReq.FromString,
                    response_serializer=v1_dot_club_dot_bot__pb2.GetBotMasterResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.club.Bot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.club.Bot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListLLM',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListLLMResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListEmbedding',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListEmbeddingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSTT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListSTT',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListSTTResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListTTS',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListTTSResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BotConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/BotConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_bot__pb2.BotConfigResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/CreateBot',
            v1_dot_ai_dot_bot__pb2.CreateBotReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.CreateBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/EditBot',
            v1_dot_ai_dot_bot__pb2.EditBotReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListBot',
            v1_dot_hi__pb2.Pagination.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBotByDids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListBotByDids',
            v1_dot_ai_dot_bot__pb2.ListBotByDidsReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListBotByDidsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/DeleteBot',
            v1_dot_ai_dot_bot__pb2.DeleteBotReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/FindBot',
            v1_dot_ai_dot_bot__pb2.FindBotReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.FindBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindBotCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/FindBotCount',
            v1_dot_ai_dot_bot__pb2.FindBotCountReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.FindBotCountResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/Transfer',
            v1_dot_ai_dot_bot__pb2.TransferReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatesToDefault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/UpdatesToDefault',
            v1_dot_ai_dot_bot__pb2.UpdatesToDefaultReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FavoriteBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/FavoriteBot',
            v1_dot_ai_dot_bot__pb2.FavoriteBotReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFavoriteBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListFavoriteBot',
            v1_dot_ai_dot_bot__pb2.ListFavoriteBotReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListFavoriteBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FavoriteBotListByDIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/FavoriteBotListByDIDs',
            v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsReq.SerializeToString,
            v1_dot_ai_dot_bot__pb2.ListFavoriteBotByDIDsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindMaster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/BindMaster',
            v1_dot_club_dot_bot__pb2.BindMasterReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnbindMaster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/UnbindMaster',
            v1_dot_club_dot_bot__pb2.UnbindMasterReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/BindStatus',
            v1_dot_club_dot_bot__pb2.BindStatusReq.SerializeToString,
            v1_dot_club_dot_bot__pb2.BindStatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllOnlineBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListAllOnlineBot',
            v1_dot_hi__pb2.Pagination.SerializeToString,
            v1_dot_club_dot_bot__pb2.ListAllOnlineBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOnlineBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/ListOnlineBot',
            v1_dot_hi__pb2.DID.SerializeToString,
            v1_dot_club_dot_bot__pb2.ListOnlineBotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBotMaster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.Bot/GetBotMaster',
            v1_dot_club_dot_bot__pb2.GetBotMasterReq.SerializeToString,
            v1_dot_club_dot_bot__pb2.GetBotMasterResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
