# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/club/login.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/club/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2
from v1.did import login_pb2 as v1_dot_did_dot_login__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13v1/club/login.proto\x12\x07hi.club\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bv1/hi.proto\x1a\x12v1/did/login.proto\"T\n\x0b\x45mbeddedReq\x12\x15\n\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x10\n\x03\x64id\x18\x02 \x01(\tR\x03\x64id\x12\x1c\n\x04node\x18\x03 \x01(\x0b\x32\x08.hi.NodeR\x04node\"\x93\x01\n\x0c\x45mbeddedResp\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x08.hi.UnitR\x04\x62\x61se\x12\x1f\n\x05token\x18\x02 \x01(\x0b\x32\t.hi.TokenR\x05token\x12\x1c\n\x04mqtt\x18\x03 \x01(\x0b\x32\x08.hi.MqttR\x04mqtt\x12\x1b\n\x06master\x18\x04 \x01(\tH\x00R\x06master\x88\x01\x01\x42\t\n\x07_master2\xd4\x01\n\x05Login\x12/\n\x08\x45mbedded\x12\x0c.hi.Web3Data\x1a\x15.hi.club.EmbeddedResp\x12\x32\n\x0cRefreshToken\x12\x17.hi.did.RefreshTokenReq\x1a\t.hi.Token\x12\x34\n\rGenerateReqId\x12\x18.hi.did.GenerateReqIdReq\x1a\t.hi.ReqID\x12\x30\n\x0cGetReqStatus\x12\t.hi.ReqID\x1a\x15.hi.did.ReqStatusRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.club.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDEDREQ']._serialized_start=94
  _globals['_EMBEDDEDREQ']._serialized_end=178
  _globals['_EMBEDDEDRESP']._serialized_start=181
  _globals['_EMBEDDEDRESP']._serialized_end=328
  _globals['_LOGIN']._serialized_start=331
  _globals['_LOGIN']._serialized_end=543
# @@protoc_insertion_point(module_scope)
