# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.club import user_pb2 as v1_dot_club_dot_user__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentUser = channel.unary_unary(
                '/hi.club.User/GetCurrentUser',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_club_dot_user__pb2.UserInfo.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/hi.club.User/UpdateUser',
                request_serializer=v1_dot_hi__pb2.Unit.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSystemMessage = channel.unary_unary(
                '/hi.club.User/ListSystemMessage',
                request_serializer=v1_dot_club_dot_user__pb2.ListSystemMessageReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_user__pb2.SystemMessages.FromString,
                _registered_method=True)
        self.DeleteSystemMessage = channel.unary_unary(
                '/hi.club.User/DeleteSystemMessage',
                request_serializer=v1_dot_club_dot_user__pb2.DeleteSystemMessageReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteAllSystemMessage = channel.unary_unary(
                '/hi.club.User/DeleteAllSystemMessage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HandleSystemMessage = channel.unary_unary(
                '/hi.club.User/HandleSystemMessage',
                request_serializer=v1_dot_club_dot_user__pb2.HandleSystemMessageReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListFriends = channel.unary_unary(
                '/hi.club.User/ListFriends',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_club_dot_user__pb2.ListFriendsResp.FromString,
                _registered_method=True)
        self.AddFriend = channel.unary_unary(
                '/hi.club.User/AddFriend',
                request_serializer=v1_dot_club_dot_user__pb2.AddFriendReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteFriend = channel.unary_unary(
                '/hi.club.User/DeleteFriend',
                request_serializer=v1_dot_club_dot_user__pb2.DeleteFriendReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListGroups = channel.unary_unary(
                '/hi.club.User/ListGroups',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_club_dot_user__pb2.ListGroupReqResp.FromString,
                _registered_method=True)
        self.GetOther = channel.unary_unary(
                '/hi.club.User/GetOther',
                request_serializer=v1_dot_club_dot_user__pb2.GetUserReq.SerializeToString,
                response_deserializer=v1_dot_hi__pb2.Unit.FromString,
                _registered_method=True)
        self.UnprocessedSysMsgCount = channel.unary_unary(
                '/hi.club.User/UnprocessedSysMsgCount',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_club_dot_user__pb2.UnprocessedSysMsgCountResp.FromString,
                _registered_method=True)


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCurrentUser(self, request, context):
        """当前用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSystemMessage(self, request, context):
        """系统消息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSystemMessage(self, request, context):
        """删除系统消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllSystemMessage(self, request, context):
        """删除所有系统消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleSystemMessage(self, request, context):
        """处理系统消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFriends(self, request, context):
        """当前用户好友
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFriend(self, request, context):
        """添加好友
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFriend(self, request, context):
        """删除好友
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroups(self, request, context):
        """机器人所在群的群Code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOther(self, request, context):
        """根据DID获取用户基本信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnprocessedSysMsgCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_club_dot_user__pb2.UserInfo.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=v1_dot_hi__pb2.Unit.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListSystemMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystemMessage,
                    request_deserializer=v1_dot_club_dot_user__pb2.ListSystemMessageReq.FromString,
                    response_serializer=v1_dot_club_dot_user__pb2.SystemMessages.SerializeToString,
            ),
            'DeleteSystemMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSystemMessage,
                    request_deserializer=v1_dot_club_dot_user__pb2.DeleteSystemMessageReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteAllSystemMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllSystemMessage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HandleSystemMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleSystemMessage,
                    request_deserializer=v1_dot_club_dot_user__pb2.HandleSystemMessageReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListFriends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFriends,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_club_dot_user__pb2.ListFriendsResp.SerializeToString,
            ),
            'AddFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFriend,
                    request_deserializer=v1_dot_club_dot_user__pb2.AddFriendReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFriend,
                    request_deserializer=v1_dot_club_dot_user__pb2.DeleteFriendReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_club_dot_user__pb2.ListGroupReqResp.SerializeToString,
            ),
            'GetOther': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOther,
                    request_deserializer=v1_dot_club_dot_user__pb2.GetUserReq.FromString,
                    response_serializer=v1_dot_hi__pb2.Unit.SerializeToString,
            ),
            'UnprocessedSysMsgCount': grpc.unary_unary_rpc_method_handler(
                    servicer.UnprocessedSysMsgCount,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_club_dot_user__pb2.UnprocessedSysMsgCountResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.club.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.club.User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/GetCurrentUser',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_club_dot_user__pb2.UserInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/UpdateUser',
            v1_dot_hi__pb2.Unit.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSystemMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/ListSystemMessage',
            v1_dot_club_dot_user__pb2.ListSystemMessageReq.SerializeToString,
            v1_dot_club_dot_user__pb2.SystemMessages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSystemMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/DeleteSystemMessage',
            v1_dot_club_dot_user__pb2.DeleteSystemMessageReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllSystemMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/DeleteAllSystemMessage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleSystemMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/HandleSystemMessage',
            v1_dot_club_dot_user__pb2.HandleSystemMessageReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFriends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/ListFriends',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_club_dot_user__pb2.ListFriendsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/AddFriend',
            v1_dot_club_dot_user__pb2.AddFriendReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/DeleteFriend',
            v1_dot_club_dot_user__pb2.DeleteFriendReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/ListGroups',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_club_dot_user__pb2.ListGroupReqResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOther(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/GetOther',
            v1_dot_club_dot_user__pb2.GetUserReq.SerializeToString,
            v1_dot_hi__pb2.Unit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnprocessedSysMsgCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.User/UnprocessedSysMsgCount',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_club_dot_user__pb2.UnprocessedSysMsgCountResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
