# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.club.tx import pc_order_pb2 as v1_dot_club_dot_tx_dot_pc__order__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


class OrderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNotPulledPcOrders = channel.unary_unary(
                '/hi.club.tx.Order/GetNotPulledPcOrders',
                request_serializer=v1_dot_hi__pb2.Web3Data.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_pc__order__pb2.GetNotPulledPcOrdersResp.FromString,
                _registered_method=True)
        self.UpdatePulledPcOrders = channel.unary_unary(
                '/hi.club.tx.Order/UpdatePulledPcOrders',
                request_serializer=v1_dot_hi__pb2.Web3Data.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class OrderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNotPulledPcOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePulledPcOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNotPulledPcOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotPulledPcOrders,
                    request_deserializer=v1_dot_hi__pb2.Web3Data.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_pc__order__pb2.GetNotPulledPcOrdersResp.SerializeToString,
            ),
            'UpdatePulledPcOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePulledPcOrders,
                    request_deserializer=v1_dot_hi__pb2.Web3Data.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.club.tx.Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.club.tx.Order', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNotPulledPcOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Order/GetNotPulledPcOrders',
            v1_dot_hi__pb2.Web3Data.SerializeToString,
            v1_dot_club_dot_tx_dot_pc__order__pb2.GetNotPulledPcOrdersResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePulledPcOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Order/UpdatePulledPcOrders',
            v1_dot_hi__pb2.Web3Data.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
