# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.club.tx import trade_pb2 as v1_dot_club_dot_tx_dot_trade__pb2


class TradeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTradeFee = channel.unary_unary(
                '/hi.club.tx.Trade/GetTradeFee',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeResp.FromString,
                _registered_method=True)
        self.GetTrade = channel.unary_unary(
                '/hi.club.tx.Trade/GetTrade',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeResp.FromString,
                _registered_method=True)
        self.AddTrade = channel.unary_unary(
                '/hi.club.tx.Trade/AddTrade',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.AddTradeReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.AddTradeResp.FromString,
                _registered_method=True)
        self.UpdateTransHash = channel.unary_unary(
                '/hi.club.tx.Trade/UpdateTransHash',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.UpdateTransHashReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListTrade = channel.unary_unary(
                '/hi.club.tx.Trade/ListTrade',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.ListTradeReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.ListTradeResp.FromString,
                _registered_method=True)
        self.ListAllTrade = channel.unary_unary(
                '/hi.club.tx.Trade/ListAllTrade',
                request_serializer=v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeReq.SerializeToString,
                response_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeResp.FromString,
                _registered_method=True)


class TradeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTradeFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTransHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTradeFee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeFee,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeReq.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeResp.SerializeToString,
            ),
            'GetTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrade,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeReq.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_trade__pb2.GetTradeResp.SerializeToString,
            ),
            'AddTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTrade,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.AddTradeReq.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_trade__pb2.AddTradeResp.SerializeToString,
            ),
            'UpdateTransHash': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTransHash,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.UpdateTransHashReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrade,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.ListTradeReq.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_trade__pb2.ListTradeResp.SerializeToString,
            ),
            'ListAllTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllTrade,
                    request_deserializer=v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeReq.FromString,
                    response_serializer=v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.club.tx.Trade', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.club.tx.Trade', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Trade(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTradeFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/GetTradeFee',
            v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeReq.SerializeToString,
            v1_dot_club_dot_tx_dot_trade__pb2.GetTradeFeeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/GetTrade',
            v1_dot_club_dot_tx_dot_trade__pb2.GetTradeReq.SerializeToString,
            v1_dot_club_dot_tx_dot_trade__pb2.GetTradeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/AddTrade',
            v1_dot_club_dot_tx_dot_trade__pb2.AddTradeReq.SerializeToString,
            v1_dot_club_dot_tx_dot_trade__pb2.AddTradeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTransHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/UpdateTransHash',
            v1_dot_club_dot_tx_dot_trade__pb2.UpdateTransHashReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/ListTrade',
            v1_dot_club_dot_tx_dot_trade__pb2.ListTradeReq.SerializeToString,
            v1_dot_club_dot_tx_dot_trade__pb2.ListTradeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.club.tx.Trade/ListAllTrade',
            v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeReq.SerializeToString,
            v1_dot_club_dot_tx_dot_trade__pb2.ListAllTradeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
