# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.ai import chat_pb2 as v1_dot_ai_dot_chat__pb2


class ChatStub(object):
    """apiKey鉴权
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simple = channel.unary_unary(
                '/hi.ai.Chat/Simple',
                request_serializer=v1_dot_ai_dot_chat__pb2.SimpleReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.DialogResp.FromString,
                _registered_method=True)
        self.GenerateCid = channel.unary_unary(
                '/hi.ai.Chat/GenerateCid',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.GenerateCidResp.FromString,
                _registered_method=True)
        self.Dialog = channel.unary_unary(
                '/hi.ai.Chat/Dialog',
                request_serializer=v1_dot_ai_dot_chat__pb2.DialogReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.DialogResp.FromString,
                _registered_method=True)
        self.DialogStream = channel.unary_stream(
                '/hi.ai.Chat/DialogStream',
                request_serializer=v1_dot_ai_dot_chat__pb2.DialogReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.DialogStreamResp.FromString,
                _registered_method=True)
        self.ClearContext = channel.unary_unary(
                '/hi.ai.Chat/ClearContext',
                request_serializer=v1_dot_ai_dot_chat__pb2.ClearContextReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/hi.ai.Chat/GetContext',
                request_serializer=v1_dot_ai_dot_chat__pb2.GetContextReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.GetContextResp.FromString,
                _registered_method=True)
        self.TextToSpeech = channel.unary_unary(
                '/hi.ai.Chat/TextToSpeech',
                request_serializer=v1_dot_ai_dot_chat__pb2.TextToSpeechReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.TextToSpeechResp.FromString,
                _registered_method=True)
        self.SpeechToText = channel.unary_unary(
                '/hi.ai.Chat/SpeechToText',
                request_serializer=v1_dot_ai_dot_chat__pb2.SpeechToTextReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.SpeechToTextResp.FromString,
                _registered_method=True)
        self.SpeechToSpeech = channel.unary_unary(
                '/hi.ai.Chat/SpeechToSpeech',
                request_serializer=v1_dot_ai_dot_chat__pb2.SpeechToSpeechReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
                _registered_method=True)
        self.SpeechToSpeech2 = channel.unary_unary(
                '/hi.ai.Chat/SpeechToSpeech2',
                request_serializer=v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
                _registered_method=True)
        self.TextToText = channel.unary_unary(
                '/hi.ai.Chat/TextToText',
                request_serializer=v1_dot_ai_dot_chat__pb2.TextToTextReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
                _registered_method=True)
        self.TextToText2 = channel.unary_unary(
                '/hi.ai.Chat/TextToText2',
                request_serializer=v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
                _registered_method=True)
        self.ListBotDelay = channel.unary_unary(
                '/hi.ai.Chat/ListBotDelay',
                request_serializer=v1_dot_ai_dot_chat__pb2.ListBotDelayReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.ListBotDelayResp.FromString,
                _registered_method=True)
        self.GetBotDelay = channel.unary_unary(
                '/hi.ai.Chat/GetBotDelay',
                request_serializer=v1_dot_ai_dot_chat__pb2.GetBotDelayReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_chat__pb2.GetBotDelayResp.FromString,
                _registered_method=True)


class ChatServicer(object):
    """apiKey鉴权
    """

    def Simple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DialogStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToSpeech2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextToText2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBotDelay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBotDelay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simple': grpc.unary_unary_rpc_method_handler(
                    servicer.Simple,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.SimpleReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.DialogResp.SerializeToString,
            ),
            'GenerateCid': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCid,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.GenerateCidResp.SerializeToString,
            ),
            'Dialog': grpc.unary_unary_rpc_method_handler(
                    servicer.Dialog,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.DialogReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.DialogResp.SerializeToString,
            ),
            'DialogStream': grpc.unary_stream_rpc_method_handler(
                    servicer.DialogStream,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.DialogReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.DialogStreamResp.SerializeToString,
            ),
            'ClearContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearContext,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.ClearContextReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.GetContextReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.GetContextResp.SerializeToString,
            ),
            'TextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.TextToSpeechReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.TextToSpeechResp.SerializeToString,
            ),
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.SpeechToTextReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.SpeechToTextResp.SerializeToString,
            ),
            'SpeechToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToSpeech,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.SpeechToSpeechReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.ChatResp.SerializeToString,
            ),
            'SpeechToSpeech2': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToSpeech2,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.ChatResp.SerializeToString,
            ),
            'TextToText': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToText,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.TextToTextReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.ChatResp.SerializeToString,
            ),
            'TextToText2': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToText2,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.ChatResp.SerializeToString,
            ),
            'ListBotDelay': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBotDelay,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.ListBotDelayReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.ListBotDelayResp.SerializeToString,
            ),
            'GetBotDelay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotDelay,
                    request_deserializer=v1_dot_ai_dot_chat__pb2.GetBotDelayReq.FromString,
                    response_serializer=v1_dot_ai_dot_chat__pb2.GetBotDelayResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.ai.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.ai.Chat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """apiKey鉴权
    """

    @staticmethod
    def Simple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/Simple',
            v1_dot_ai_dot_chat__pb2.SimpleReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.DialogResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/GenerateCid',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_ai_dot_chat__pb2.GenerateCidResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/Dialog',
            v1_dot_ai_dot_chat__pb2.DialogReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.DialogResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DialogStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hi.ai.Chat/DialogStream',
            v1_dot_ai_dot_chat__pb2.DialogReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.DialogStreamResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/ClearContext',
            v1_dot_ai_dot_chat__pb2.ClearContextReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/GetContext',
            v1_dot_ai_dot_chat__pb2.GetContextReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.GetContextResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/TextToSpeech',
            v1_dot_ai_dot_chat__pb2.TextToSpeechReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.TextToSpeechResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/SpeechToText',
            v1_dot_ai_dot_chat__pb2.SpeechToTextReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.SpeechToTextResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/SpeechToSpeech',
            v1_dot_ai_dot_chat__pb2.SpeechToSpeechReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechToSpeech2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/SpeechToSpeech2',
            v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/TextToText',
            v1_dot_ai_dot_chat__pb2.TextToTextReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextToText2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/TextToText2',
            v1_dot_ai_dot_chat__pb2.ToolCallResultsReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBotDelay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/ListBotDelay',
            v1_dot_ai_dot_chat__pb2.ListBotDelayReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.ListBotDelayResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBotDelay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.Chat/GetBotDelay',
            v1_dot_ai_dot_chat__pb2.GetBotDelayReq.SerializeToString,
            v1_dot_ai_dot_chat__pb2.GetBotDelayResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
