# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/ai/login.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/ai/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v1 import hi_pb2 as v1_dot_hi__pb2
from v1.did import login_pb2 as v1_dot_did_dot_login__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11v1/ai/login.proto\x12\x05hi.ai\x1a\x0bv1/hi.proto\x1a\x12v1/did/login.proto2\xa3\x01\n\x05Login\x12\x32\n\x0cRefreshToken\x12\x17.hi.did.RefreshTokenReq\x1a\t.hi.Token\x12\x34\n\rGenerateReqId\x12\x18.hi.did.GenerateReqIdReq\x1a\t.hi.ReqID\x12\x30\n\x0cGetReqStatus\x12\t.hi.ReqID\x1a\x15.hi.did.ReqStatusRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.ai.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGIN']._serialized_start=62
  _globals['_LOGIN']._serialized_end=225
# @@protoc_insertion_point(module_scope)
