# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/hi.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/hi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bv1/hi.proto\x12\x02hi\"<\n\x08Web3Data\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta\x12\x1c\n\tsignature\x18\x02 \x01(\tR\tsignature\"\x15\n\x03\x44ID\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"p\n\x04Unit\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n\x03\x64id\x18\x02 \x01(\tR\x03\x64id\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n\x06\x61vatar\x18\x04 \x01(\tR\x06\x61vatar\x12\x16\n\x06update\x18\x05 \x01(\x03R\x06update\"N\n\x04Mqtt\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x03 \x01(\tR\x08password\"B\n\x05Token\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12#\n\rrefresh_token\x18\x02 \x01(\tR\x0crefreshToken\"\x1d\n\x05Nonce\x12\x14\n\x05nonce\x18\x01 \x01(\tR\x05nonce\"\x17\n\x05ReqID\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n\x05State\x12\x14\n\x05state\x18\x01 \x01(\x08R\x05state\"\x16\n\x06Number\x12\x0c\n\x01n\x18\x01 \x01(\x03R\x01n\"<\n\x04Node\x12\x10\n\x03\x61pp\x18\x01 \x01(\tR\x03\x61pp\x12\x10\n\x03\x64\x65v\x18\x02 \x01(\tR\x03\x64\x65v\x12\x10\n\x03mac\x18\x03 \x01(\tR\x03mac\"6\n\nPagination\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n\x05limit\x18\x02 \x01(\x05R\x05limitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.hi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEB3DATA']._serialized_start=19
  _globals['_WEB3DATA']._serialized_end=79
  _globals['_DID']._serialized_start=81
  _globals['_DID']._serialized_end=102
  _globals['_UNIT']._serialized_start=104
  _globals['_UNIT']._serialized_end=216
  _globals['_MQTT']._serialized_start=218
  _globals['_MQTT']._serialized_end=296
  _globals['_TOKEN']._serialized_start=298
  _globals['_TOKEN']._serialized_end=364
  _globals['_NONCE']._serialized_start=366
  _globals['_NONCE']._serialized_end=395
  _globals['_REQID']._serialized_start=397
  _globals['_REQID']._serialized_end=420
  _globals['_STATE']._serialized_start=422
  _globals['_STATE']._serialized_end=451
  _globals['_NUMBER']._serialized_start=453
  _globals['_NUMBER']._serialized_end=475
  _globals['_NODE']._serialized_start=477
  _globals['_NODE']._serialized_end=537
  _globals['_PAGINATION']._serialized_start=539
  _globals['_PAGINATION']._serialized_end=593
# @@protoc_insertion_point(module_scope)
