# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.did import base_pb2 as v1_dot_did_dot_base__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


class BaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCoins = channel.unary_unary(
                '/hi.did.Base/ListCoins',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_did_dot_base__pb2.ListCoinsResp.FromString,
                _registered_method=True)
        self.TotalUsers = channel.unary_unary(
                '/hi.did.Base/TotalUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_hi__pb2.Number.FromString,
                _registered_method=True)
        self.LastetVersion = channel.unary_unary(
                '/hi.did.Base/LastetVersion',
                request_serializer=v1_dot_did_dot_base__pb2.LastetVersionReq.SerializeToString,
                response_deserializer=v1_dot_did_dot_base__pb2.LastetVersionResp.FromString,
                _registered_method=True)
        self.ListSuperAdminUsers = channel.unary_unary(
                '/hi.did.Base/ListSuperAdminUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_did_dot_base__pb2.ListSuperAdminUsersResp.FromString,
                _registered_method=True)


class BaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCoins(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TotalUsers(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LastetVersion(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSuperAdminUsers(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCoins,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_did_dot_base__pb2.ListCoinsResp.SerializeToString,
            ),
            'TotalUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_hi__pb2.Number.SerializeToString,
            ),
            'LastetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.LastetVersion,
                    request_deserializer=v1_dot_did_dot_base__pb2.LastetVersionReq.FromString,
                    response_serializer=v1_dot_did_dot_base__pb2.LastetVersionResp.SerializeToString,
            ),
            'ListSuperAdminUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSuperAdminUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_did_dot_base__pb2.ListSuperAdminUsersResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.did.Base', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.did.Base', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Base(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Base/ListCoins',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_did_dot_base__pb2.ListCoinsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TotalUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Base/TotalUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_hi__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LastetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Base/LastetVersion',
            v1_dot_did_dot_base__pb2.LastetVersionReq.SerializeToString,
            v1_dot_did_dot_base__pb2.LastetVersionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSuperAdminUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Base/ListSuperAdminUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_did_dot_base__pb2.ListSuperAdminUsersResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AssistStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifySignature = channel.unary_unary(
                '/hi.did.Assist/VerifySignature',
                request_serializer=v1_dot_hi__pb2.Web3Data.SerializeToString,
                response_deserializer=v1_dot_hi__pb2.DID.FromString,
                _registered_method=True)


class AssistServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerifySignature(self, request, context):
        """Web3鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=v1_dot_hi__pb2.Web3Data.FromString,
                    response_serializer=v1_dot_hi__pb2.DID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.did.Assist', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.did.Assist', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Assist(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Assist/VerifySignature',
            v1_dot_hi__pb2.Web3Data.SerializeToString,
            v1_dot_hi__pb2.DID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
