# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/did/extend.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/did/extend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13v1/did/extend.proto\x12\x06hi.did\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x15UserExtendSettingResp\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n\x05table\x18\x03 \x01(\tR\x05table\"f\n\x0eUserExtendInfo\x12\x12\n\x04logo\x18\x01 \x01(\tR\x04logo\x12\x14\n\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n\x04\x63\x61rd\x18\x03 \x01(\tR\x04\x63\x61rd\x12\x16\n\x06\x65xtend\x18\x04 \x01(\tR\x06\x65xtend\"\x91\x01\n\x13UserExtendUpdateReq\x12\x34\n\x04unit\x18\x02 \x03(\x0b\x32 .hi.did.UserExtendUpdateReq.UnitR\x04unit\x1a\x44\n\x04Unit\x12\x10\n\x03\x64id\x18\x01 \x01(\tR\x03\x64id\x12*\n\x04info\x18\x02 \x01(\x0b\x32\x16.hi.did.UserExtendInfoR\x04info\"\'\n\x11UserExtendListReq\x12\x12\n\x04list\x18\x01 \x03(\tR\x04list\"\x8f\x01\n\x12UserExtendListResp\x12\x33\n\x04unit\x18\x02 \x03(\x0b\x32\x1f.hi.did.UserExtendListResp.UnitR\x04unit\x1a\x44\n\x04Unit\x12\x10\n\x03\x64id\x18\x01 \x01(\tR\x03\x64id\x12*\n\x04info\x18\x02 \x01(\x0b\x32\x16.hi.did.UserExtendInfoR\x04info\")\n\x13UserExtendDeleteReq\x12\x12\n\x04list\x18\x01 \x03(\tR\x04list2\x92\x01\n\x11UserExtendSetting\x12?\n\x06Update\x12\x16.google.protobuf.Empty\x1a\x1d.hi.did.UserExtendSettingResp\x12<\n\x03Get\x12\x16.google.protobuf.Empty\x1a\x1d.hi.did.UserExtendSettingResp2\xc9\x01\n\nUserExtend\x12=\n\x06Update\x12\x1b.hi.did.UserExtendUpdateReq\x1a\x16.google.protobuf.Empty\x12=\n\x04List\x12\x19.hi.did.UserExtendListReq\x1a\x1a.hi.did.UserExtendListResp\x12=\n\x06\x44\x65lete\x12\x1b.hi.did.UserExtendDeleteReq\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.did.extend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USEREXTENDSETTINGRESP']._serialized_start=60
  _globals['_USEREXTENDSETTINGRESP']._serialized_end=127
  _globals['_USEREXTENDINFO']._serialized_start=129
  _globals['_USEREXTENDINFO']._serialized_end=231
  _globals['_USEREXTENDUPDATEREQ']._serialized_start=234
  _globals['_USEREXTENDUPDATEREQ']._serialized_end=379
  _globals['_USEREXTENDUPDATEREQ_UNIT']._serialized_start=311
  _globals['_USEREXTENDUPDATEREQ_UNIT']._serialized_end=379
  _globals['_USEREXTENDLISTREQ']._serialized_start=381
  _globals['_USEREXTENDLISTREQ']._serialized_end=420
  _globals['_USEREXTENDLISTRESP']._serialized_start=423
  _globals['_USEREXTENDLISTRESP']._serialized_end=566
  _globals['_USEREXTENDLISTRESP_UNIT']._serialized_start=311
  _globals['_USEREXTENDLISTRESP_UNIT']._serialized_end=379
  _globals['_USEREXTENDDELETEREQ']._serialized_start=568
  _globals['_USEREXTENDDELETEREQ']._serialized_end=609
  _globals['_USEREXTENDSETTING']._serialized_start=612
  _globals['_USEREXTENDSETTING']._serialized_end=758
  _globals['_USEREXTEND']._serialized_start=761
  _globals['_USEREXTEND']._serialized_end=962
# @@protoc_insertion_point(module_scope)
