# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/did/login.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/did/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12v1/did/login.proto\x12\x06hi.did\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bv1/hi.proto\"f\n\x0fRefreshTokenReq\x12\x1c\n\x04node\x18\x01 \x01(\x0b\x32\x08.hi.NodeR\x04node\x12\x10\n\x03\x64id\x18\x02 \x01(\tR\x03\x64id\x12#\n\rrefresh_token\x18\x03 \x01(\tR\x0crefreshToken\"e\n\x08LoginReq\x12\x19\n\x03\x64id\x18\x01 \x01(\x0b\x32\x07.hi.DIDR\x03\x64id\x12\x1c\n\x04node\x18\x02 \x01(\x0b\x32\x08.hi.NodeR\x04node\x12 \n\x06req_id\x18\x03 \x01(\x0b\x32\t.hi.ReqIDR\x05reqId\"h\n\tLoginResp\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x08.hi.UnitR\x04user\x12\x1f\n\x05token\x18\x02 \x01(\x0b\x32\t.hi.TokenR\x05token\x12\x1c\n\x04mqtt\x18\x03 \x01(\x0b\x32\x08.hi.MqttR\x04mqtt\"B\n\x10GenerateReqIdReq\x12\x10\n\x03\x64id\x18\x01 \x01(\tR\x03\x64id\x12\x1c\n\x04node\x18\x02 \x01(\x0b\x32\x08.hi.NodeR\x04node\"\x84\x01\n\rReqStatusResp\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x08.hi.UnitR\x04\x62\x61se\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n\x05token\x18\x03 \x01(\x0b\x32\t.hi.TokenR\x05token\x12\x1c\n\x04mqtt\x18\x04 \x01(\x0b\x32\x08.hi.MqttR\x04mqtt2\xb8\x02\n\x05Login\x12\x32\n\x0cRefreshToken\x12\x17.hi.did.RefreshTokenReq\x1a\t.hi.Token\x12)\n\x06Verify\x12\x0c.hi.Web3Data\x1a\x11.hi.did.LoginResp\x12\x34\n\rGenerateReqId\x12\x18.hi.did.GenerateReqIdReq\x1a\t.hi.ReqID\x12\x30\n\x0cGetReqStatus\x12\t.hi.ReqID\x1a\x15.hi.did.ReqStatusResp\x12.\n\x06Notify\x12\x0c.hi.Web3Data\x1a\x16.google.protobuf.Empty\x12\x38\n\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.did.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFRESHTOKENREQ']._serialized_start=72
  _globals['_REFRESHTOKENREQ']._serialized_end=174
  _globals['_LOGINREQ']._serialized_start=176
  _globals['_LOGINREQ']._serialized_end=277
  _globals['_LOGINRESP']._serialized_start=279
  _globals['_LOGINRESP']._serialized_end=383
  _globals['_GENERATEREQIDREQ']._serialized_start=385
  _globals['_GENERATEREQIDREQ']._serialized_end=451
  _globals['_REQSTATUSRESP']._serialized_start=454
  _globals['_REQSTATUSRESP']._serialized_end=586
  _globals['_LOGIN']._serialized_start=589
  _globals['_LOGIN']._serialized_end=901
# @@protoc_insertion_point(module_scope)
