# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/did/pay.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/did/pay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v1/did/pay.proto\x12\x06hi.did\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bv1/hi.proto\"=\n\x05Order\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n\x03\x64id\x18\x02 \x01(\tR\x03\x64id\x12\x12\n\x04hash\x18\x03 \x01(\tR\x04hash2Y\n\x03Pay\x12\"\n\x0bGenerateReq\x12\x08.hi.Node\x1a\t.hi.ReqID\x12.\n\x06Notify\x12\x0c.hi.Web3Data\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.did.pay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=70
  _globals['_ORDER']._serialized_end=131
  _globals['_PAY']._serialized_start=133
  _globals['_PAY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
