# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


class PayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReq = channel.unary_unary(
                '/hi.did.Pay/GenerateReq',
                request_serializer=v1_dot_hi__pb2.Node.SerializeToString,
                response_deserializer=v1_dot_hi__pb2.ReqID.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/hi.did.Pay/Notify',
                request_serializer=v1_dot_hi__pb2.Web3Data.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateReq(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Order // Web3鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReq': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReq,
                    request_deserializer=v1_dot_hi__pb2.Node.FromString,
                    response_serializer=v1_dot_hi__pb2.ReqID.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=v1_dot_hi__pb2.Web3Data.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.did.Pay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.did.Pay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Pay/GenerateReq',
            v1_dot_hi__pb2.Node.SerializeToString,
            v1_dot_hi__pb2.ReqID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Pay/Notify',
            v1_dot_hi__pb2.Web3Data.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
