# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.did import price_pb2 as v1_dot_did_dot_price__pb2


class PriceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrice = channel.unary_unary(
                '/hi.did.Price/GetPrice',
                request_serializer=v1_dot_did_dot_price__pb2.GetPriceReq.SerializeToString,
                response_deserializer=v1_dot_did_dot_price__pb2.GetPriceResp.FromString,
                _registered_method=True)


class PriceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrice(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=v1_dot_did_dot_price__pb2.GetPriceReq.FromString,
                    response_serializer=v1_dot_did_dot_price__pb2.GetPriceResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.did.Price', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.did.Price', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Price(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Price/GetPrice',
            v1_dot_did_dot_price__pb2.GetPriceReq.SerializeToString,
            v1_dot_did_dot_price__pb2.GetPriceResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
