# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.did import trans_pb2 as v1_dot_did_dot_trans__pb2


class TransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTransactions = channel.unary_unary(
                '/hi.did.Transfer/ListTransactions',
                request_serializer=v1_dot_did_dot_trans__pb2.ListTransactionsReq.SerializeToString,
                response_deserializer=v1_dot_did_dot_trans__pb2.ListTransactionsResp.FromString,
                _registered_method=True)
        self.GetTransactionDetail = channel.unary_unary(
                '/hi.did.Transfer/GetTransactionDetail',
                request_serializer=v1_dot_did_dot_trans__pb2.GetTransactionDetailReq.SerializeToString,
                response_deserializer=v1_dot_did_dot_trans__pb2.GetTransactionDetailResp.FromString,
                _registered_method=True)


class TransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTransactions(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionDetail(self, request, context):
        """不鉴权
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransactions,
                    request_deserializer=v1_dot_did_dot_trans__pb2.ListTransactionsReq.FromString,
                    response_serializer=v1_dot_did_dot_trans__pb2.ListTransactionsResp.SerializeToString,
            ),
            'GetTransactionDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionDetail,
                    request_deserializer=v1_dot_did_dot_trans__pb2.GetTransactionDetailReq.FromString,
                    response_serializer=v1_dot_did_dot_trans__pb2.GetTransactionDetailResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.did.Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.did.Transfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Transfer/ListTransactions',
            v1_dot_did_dot_trans__pb2.ListTransactionsReq.SerializeToString,
            v1_dot_did_dot_trans__pb2.ListTransactionsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.did.Transfer/GetTransactionDetail',
            v1_dot_did_dot_trans__pb2.GetTransactionDetailReq.SerializeToString,
            v1_dot_did_dot_trans__pb2.GetTransactionDetailResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
