# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1.ai.plugin import plugin_pb2 as v1_dot_ai_dot_plugin_dot_plugin__pb2


class AiPluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/hi.ai.plugin.AiPlugin/Search',
                request_serializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchResp.FromString,
                _registered_method=True)
        self.Python = channel.unary_unary(
                '/hi.ai.plugin.AiPlugin/Python',
                request_serializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonReq.SerializeToString,
                response_deserializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonResp.FromString,
                _registered_method=True)


class AiPluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Python(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchReq.FromString,
                    response_serializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchResp.SerializeToString,
            ),
            'Python': grpc.unary_unary_rpc_method_handler(
                    servicer.Python,
                    request_deserializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonReq.FromString,
                    response_serializer=v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi.ai.plugin.AiPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hi.ai.plugin.AiPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiPlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.plugin.AiPlugin/Search',
            v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchReq.SerializeToString,
            v1_dot_ai_dot_plugin_dot_plugin__pb2.SearchResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Python(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hi.ai.plugin.AiPlugin/Python',
            v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonReq.SerializeToString,
            v1_dot_ai_dot_plugin_dot_plugin__pb2.PythonResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
