# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/club/ai/train.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/club/ai/train.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2
from v1.ai import train_pb2 as v1_dot_ai_dot_train__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16v1/club/ai/train.proto\x12\nhi.club.ai\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bv1/hi.proto\x1a\x11v1/ai/train.proto2\x98\x07\n\x0b\x42otTraining\x12<\n\x0bTrainingBot\x12\x15.hi.ai.TrainingBotReq\x1a\x16.google.protobuf.Empty\x12\x45\n\x0eTrainingStatus\x12\x18.hi.ai.TrainingStatusReq\x1a\x19.hi.ai.TrainingStatusResp\x12@\n\rTrainingClear\x12\x17.hi.ai.TrainingClearReq\x1a\x16.google.protobuf.Empty\x12:\n\nUploadFile\x12\x14.hi.ai.UploadFileReq\x1a\x16.google.protobuf.Empty\x12<\n\x0bListBotFile\x12\x15.hi.ai.ListBotFileReq\x1a\x16.hi.ai.ListBotFileResp\x12@\n\rDeleteBotFile\x12\x17.hi.ai.DeleteBotFileReq\x1a\x16.google.protobuf.Empty\x12\x42\n\x0e\x44\x65leteBotFiles\x12\x18.hi.ai.DeleteBotFilesReq\x1a\x16.google.protobuf.Empty\x12L\n\x13\x44\x65leteBotFilesByDid\x12\x1d.hi.ai.DeleteBotFilesByDidReq\x1a\x16.google.protobuf.Empty\x12\x39\n\nGetBotFile\x12\x14.hi.ai.GetBotFileReq\x1a\x15.hi.ai.GetBotFileResp\x12?\n\rUpdateContent\x12\x16.hi.ai.UpdateCotentReq\x1a\x16.google.protobuf.Empty\x12@\n\rCreateContent\x12\x16.hi.ai.CreateCotentReq\x1a\x17.hi.ai.CreateCotentResp\x12:\n\nEditDegest\x12\x14.hi.ai.EditDigestReq\x1a\x16.google.protobuf.Empty\x12<\n\x0bSetMemModel\x12\x15.hi.ai.SetMemModelReq\x1a\x16.google.protobuf.Empty\x12<\n\x0bGetMemModel\x12\x15.hi.ai.GetMemModelReq\x1a\x16.hi.ai.GetMemModelRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.club.ai.train_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOTTRAINING']._serialized_start=100
  _globals['_BOTTRAINING']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
