# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/club/firebase/firebase.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/club/firebase/firebase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import hi_pb2 as v1_dot_hi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fv1/club/firebase/firebase.proto\x12\x10hi.club.firebase\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bv1/hi.proto\"E\n\x0fPushRegisterReq\x12\x1c\n\x04node\x18\x01 \x01(\x0b\x32\x08.hi.NodeR\x04node\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\")\n\x11PushUnregisterReq\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token2\x9f\x01\n\x0bPushManager\x12\x45\n\x08Register\x12!.hi.club.firebase.PushRegisterReq\x1a\x16.google.protobuf.Empty\x12I\n\nUnregister\x12#.hi.club.firebase.PushUnregisterReq\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.club.firebase.firebase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHREGISTERREQ']._serialized_start=95
  _globals['_PUSHREGISTERREQ']._serialized_end=164
  _globals['_PUSHUNREGISTERREQ']._serialized_start=166
  _globals['_PUSHUNREGISTERREQ']._serialized_end=207
  _globals['_PUSHMANAGER']._serialized_start=210
  _globals['_PUSHMANAGER']._serialized_end=369
# @@protoc_insertion_point(module_scope)
