syntax = "proto3";

package hi.did;

import "google/protobuf/any.proto";
import "hi/common.proto";

option go_package = "github.com/HiWorld-56/hi-proto/gen/go/hi/did";

message Packet {
  oneof kind {
    Notice notice = 1;
  }
}

/* extra:
   Transaction
   notes:
   update_xxx => ["name", "avatar", "background", ...]
*/
message Extra {
  google.protobuf.Any extra = 1;
  repeated string notes = 2;
}

/*
   type:
   transaction: 其他人向自己发起交易
*/
message Notice {
  string uuid = 1;
  string type = 2;
  hi.Entity from = 3;
  Extra extra = 4;
}
