# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/ai/endpoint/endpoint.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/ai/endpoint/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dv1/ai/endpoint/endpoint.proto\x12\x0ehi.ai.endpoint\x1a\x1bgoogle/protobuf/empty.proto\",\n\x0e\x45ndpointSetReq\x12\x1a\n\x08\x65ndpoint\x18\x01 \x01(\tR\x08\x65ndpoint\"-\n\x0f\x45ndpointGetResp\x12\x1a\n\x08\x65ndpoint\x18\x01 \x01(\tR\x08\x65ndpoint2\x8f\x01\n\x0ePluginEndpoint\x12=\n\x03Set\x12\x1e.hi.ai.endpoint.EndpointSetReq\x1a\x16.google.protobuf.Empty\x12>\n\x03Get\x12\x16.google.protobuf.Empty\x1a\x1f.hi.ai.endpoint.EndpointGetRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.ai.endpoint.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENDPOINTSETREQ']._serialized_start=78
  _globals['_ENDPOINTSETREQ']._serialized_end=122
  _globals['_ENDPOINTGETRESP']._serialized_start=124
  _globals['_ENDPOINTGETRESP']._serialized_end=169
  _globals['_PLUGINENDPOINT']._serialized_start=172
  _globals['_PLUGINENDPOINT']._serialized_end=315
# @@protoc_insertion_point(module_scope)
